#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from yacc.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 11 "yacc.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void reset();
void declare_initalize(int id, int type_);
void declare_only(int id, int type_);
void assign_only(int id);
void declare_const(int id, int type);
void calc_lowp(char*);
void calc_highp(char*);
void cond_lowp(char*);
void cond_highp(char*);
void switch_test ();
void open_brace();
void close_brace ();
void switch_expr();
void print_symbol_table();
char * get_type(int type);

int new_scope();
int exit_scope();
int opened_scopes = 0;
int nesting_arr[100];
int nesting_last_index = -1;

int exitFlag=0;
int next_reg = 1; // The register number to be written in the next instruction
int next_cond_reg = 11;
int first_for = 1;
int is_first = 1; // check if is the first operation for consistent register counts
int is_first_cond = 1;
int after_hp = 0; // a high priority operation is done
int after_hp_cond = 0; // a high priority operation is done
int declared[26];
int is_constant[26];// for each variable store 1 if it constant
int scope[26]; // a scope number for each variable
int cscope = 0;
int next_case = 0;
int current_scope = 0;
int variable_initialized[26];
int type[26];

#line 56 "yacc.y"
typedef union {int INTGR; char * STRNG; float FLT; char CHR;} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	ELSE	259
#define	ELSEIF	260
#define	FOR	261
#define	WHILE	262
#define	SWITCH	263
#define	CASE	264
#define	DO	265
#define	BREAK	266
#define	DEFAULT	267
#define	TYPE_INT	268
#define	TYPE_FLT	269
#define	TYPE_STR	270
#define	TYPE_CHR	271
#define	TYPE_CONST	272
#define	show_symbol_table	273
#define	ID	274
#define	NUM	275
#define	FLOATING_NUM	276
#define	CHAR_VALUE	277
#define	STRING_VALUE	278
#define	exit_command	279
#define	AND	280
#define	OR	281
#define	NOT	282
#define	EQ	283
#define	NOTEQ	284
#define	GTE	285
#define	LTE	286
#define	GT	287
#define	LT	288
#define	INC	289
#define	DEC	290


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int ELSE;
static const int ELSEIF;
static const int FOR;
static const int WHILE;
static const int SWITCH;
static const int CASE;
static const int DO;
static const int BREAK;
static const int DEFAULT;
static const int TYPE_INT;
static const int TYPE_FLT;
static const int TYPE_STR;
static const int TYPE_CHR;
static const int TYPE_CONST;
static const int show_symbol_table;
static const int ID;
static const int NUM;
static const int FLOATING_NUM;
static const int CHAR_VALUE;
static const int STRING_VALUE;
static const int exit_command;
static const int AND;
static const int OR;
static const int NOT;
static const int EQ;
static const int NOTEQ;
static const int GTE;
static const int LTE;
static const int GT;
static const int LT;
static const int INC;
static const int DEC;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,ELSE=259
	,ELSEIF=260
	,FOR=261
	,WHILE=262
	,SWITCH=263
	,CASE=264
	,DO=265
	,BREAK=266
	,DEFAULT=267
	,TYPE_INT=268
	,TYPE_FLT=269
	,TYPE_STR=270
	,TYPE_CHR=271
	,TYPE_CONST=272
	,show_symbol_table=273
	,ID=274
	,NUM=275
	,FLOATING_NUM=276
	,CHAR_VALUE=277
	,STRING_VALUE=278
	,exit_command=279
	,AND=280
	,OR=281
	,NOT=282
	,EQ=283
	,NOTEQ=284
	,GTE=285
	,LTE=286
	,GT=287
	,LT=288
	,INC=289
	,DEC=290


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::ELSE=259;
const int YY_parse_CLASS::ELSEIF=260;
const int YY_parse_CLASS::FOR=261;
const int YY_parse_CLASS::WHILE=262;
const int YY_parse_CLASS::SWITCH=263;
const int YY_parse_CLASS::CASE=264;
const int YY_parse_CLASS::DO=265;
const int YY_parse_CLASS::BREAK=266;
const int YY_parse_CLASS::DEFAULT=267;
const int YY_parse_CLASS::TYPE_INT=268;
const int YY_parse_CLASS::TYPE_FLT=269;
const int YY_parse_CLASS::TYPE_STR=270;
const int YY_parse_CLASS::TYPE_CHR=271;
const int YY_parse_CLASS::TYPE_CONST=272;
const int YY_parse_CLASS::show_symbol_table=273;
const int YY_parse_CLASS::ID=274;
const int YY_parse_CLASS::NUM=275;
const int YY_parse_CLASS::FLOATING_NUM=276;
const int YY_parse_CLASS::CHAR_VALUE=277;
const int YY_parse_CLASS::STRING_VALUE=278;
const int YY_parse_CLASS::exit_command=279;
const int YY_parse_CLASS::AND=280;
const int YY_parse_CLASS::OR=281;
const int YY_parse_CLASS::NOT=282;
const int YY_parse_CLASS::EQ=283;
const int YY_parse_CLASS::NOTEQ=284;
const int YY_parse_CLASS::GTE=285;
const int YY_parse_CLASS::LTE=286;
const int YY_parse_CLASS::GT=287;
const int YY_parse_CLASS::LT=288;
const int YY_parse_CLASS::INC=289;
const int YY_parse_CLASS::DEC=290;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		200
#define	YYFLAG		-32768
#define	YYNTBASE	51

#define YYTRANSLATE(x) ((unsigned)(x) <= 290 ? yytranslate[x] : 89)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    27,     2,    45,
    46,    31,    29,     2,    30,     2,    32,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    47,    44,     2,
    50,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    26,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    48,    28,    49,    25,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    33,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     6,     9,    11,    14,    17,    20,    24,    28,
    32,    35,    39,    43,    48,    53,    57,    59,    61,    63,
    65,    67,    68,    75,    76,    81,    82,    88,    89,    90,
    98,   101,   102,   105,   109,   110,   111,   122,   134,   136,
   138,   140,   142,   143,   152,   154,   156,   164,   175,   185,
   188,   190,   192,   196,   200,   204,   207,   209,   213,   217,
   221,   225,   229,   233,   237,   241,   245,   248,   252,   256,
   260,   262,   266,   270,   272,   274,   276,   278,   282,   286,
   289,   292,   295,   300,   305,   310,   315,   317,   319,   325,
   331
};

static const short yyrhs[] = {    85,
    44,     0,    84,    44,     0,    88,    44,     0,    52,     0,
    81,    44,     0,    24,    44,     0,    18,    44,     0,    51,
    85,    44,     0,    51,    84,    44,     0,    51,    88,    44,
     0,    51,    52,     0,    51,    81,    44,     0,    51,    24,
    44,     0,    86,    51,    87,    51,     0,    51,    86,    51,
    87,     0,    51,    18,    44,     0,    75,     0,    71,     0,
    66,     0,    63,     0,    53,     0,     0,     8,    45,    81,
    46,    54,    55,     0,     0,    86,    58,    56,    87,     0,
     0,    86,    58,    62,    57,    87,     0,     0,     0,     9,
    59,    81,    60,    47,    51,    61,     0,    58,    58,     0,
     0,    11,    44,     0,    12,    47,    51,     0,     0,     0,
    10,    48,    64,    51,    49,    65,     7,    45,    79,    46,
     0,     6,    45,    84,    67,    79,    68,    84,    46,    69,
    51,    70,     0,    44,     0,    44,     0,    48,     0,    49,
     0,     0,     7,    72,    45,    79,    46,    73,    51,    74,
     0,    48,     0,    49,     0,     3,    45,    79,    46,    77,
    51,    78,     0,     3,    45,    79,    46,    77,    51,    78,
    76,    51,    78,     0,     3,    45,    79,    46,    77,    51,
    78,     4,    75,     0,     4,    48,     0,    48,     0,    49,
     0,    45,    79,    46,     0,    79,    34,    80,     0,    79,
    33,    80,     0,    35,    79,     0,    80,     0,    81,    36,
    81,     0,    81,    37,    81,     0,    81,    38,    81,     0,
    81,    40,    81,     0,    81,    39,    81,     0,    81,    41,
    81,     0,    45,    81,    46,     0,    81,    29,    82,     0,
    81,    30,    82,     0,    25,    81,     0,    81,    28,    82,
     0,    81,    27,    82,     0,    81,    26,    82,     0,    82,
     0,    82,    31,    83,     0,    82,    32,    83,     0,    83,
     0,    20,     0,    21,     0,    19,     0,    45,    81,    46,
     0,    19,    50,    81,     0,    13,    19,     0,    14,    19,
     0,    16,    19,     0,    13,    19,    50,    81,     0,    14,
    19,    50,    81,     0,    16,    19,    50,    22,     0,    16,
    19,    50,    21,     0,    48,     0,    49,     0,    17,    13,
    19,    50,    81,     0,    17,    14,    19,    50,    81,     0,
    17,    16,    19,    50,    22,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    78,    79,    80,    81,    82,    83,    84,    85,    86,    87,
    88,    89,    90,    91,    92,    93,    96,    98,    99,   100,
   101,   103,   105,   106,   108,   108,   109,   109,   112,   112,
   113,   115,   116,   117,   119,   119,   119,   120,   122,   124,
   127,   131,   136,   137,   139,   140,   142,   144,   145,   147,
   148,   149,   152,   154,   155,   156,   157,   160,   162,   163,
   164,   165,   166,   170,   172,   173,   174,   181,   182,   183,
   184,   187,   188,   189,   193,   195,   197,   209,   211,   215,
   217,   218,   219,   220,   221,   233,   236,   237,   240,   244,
   246
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","ELSE",
"ELSEIF","FOR","WHILE","SWITCH","CASE","DO","BREAK","DEFAULT","TYPE_INT","TYPE_FLT",
"TYPE_STR","TYPE_CHR","TYPE_CONST","show_symbol_table","ID","NUM","FLOATING_NUM",
"CHAR_VALUE","STRING_VALUE","exit_command","'~'","'^'","'&'","'|'","'+'","'-'",
"'*'","'/'","AND","OR","NOT","EQ","NOTEQ","GTE","LTE","GT","LT","INC","DEC",
"';'","'('","')'","':'","'{'","'}'","'='","statement","conditional_statement",
"switch_statement","@1","switch_body","@2","@3","cases","@4","@5","case_break",
"default","do_while","@6","@7","for_loop","for_sep1","for_sep2","for_ob","for_cb",
"while_loop","@8","while_open_brace","while_closed_brace","if_statement","ELSE_FINAL",
"if_open_brace","if_closed_brace","condition","high_p_condition","math_expr",
"high_priority_expr","math_element","assign_statement","variable_declaration_statement",
"open_brace","close_brace","constant_declaration_statement",""
};
#endif

static const short yyr1[] = {     0,
    51,    51,    51,    51,    51,    51,    51,    51,    51,    51,
    51,    51,    51,    51,    51,    51,    52,    52,    52,    52,
    52,    54,    53,    56,    55,    57,    55,    59,    60,    58,
    58,    61,    61,    62,    64,    65,    63,    66,    67,    68,
    69,    70,    72,    71,    73,    74,    75,    75,    75,    76,
    77,    78,    79,    79,    79,    79,    79,    80,    80,    80,
    80,    80,    80,    81,    81,    81,    81,    81,    81,    81,
    81,    82,    82,    82,    83,    83,    83,    83,    84,    85,
    85,    85,    85,    85,    85,    85,    86,    87,    88,    88,
    88
};

static const short yyr2[] = {     0,
     2,     2,     2,     1,     2,     2,     2,     3,     3,     3,
     2,     3,     3,     4,     4,     3,     1,     1,     1,     1,
     1,     0,     6,     0,     4,     0,     5,     0,     0,     7,
     2,     0,     2,     3,     0,     0,    10,    11,     1,     1,
     1,     1,     0,     8,     1,     1,     7,    10,     9,     2,
     1,     1,     3,     3,     3,     2,     1,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     2,     3,     3,     3,
     1,     3,     3,     1,     1,     1,     1,     3,     3,     2,
     2,     2,     4,     4,     4,     4,     1,     1,     5,     5,
     5
};

static const short yydefact[] = {     0,
     0,     0,    43,     0,     0,     0,     0,     0,     0,     0,
    77,    75,    76,     0,     0,     0,    87,     0,     4,    21,
    20,    19,    18,    17,     0,    71,    74,     0,     0,     0,
     0,     0,     0,     0,     0,    35,    80,    81,    82,     0,
     0,     0,     7,     0,     6,    77,    67,     0,     0,     0,
    11,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     5,     0,     0,     2,     1,     0,     3,     0,     0,
     0,    57,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    79,    64,    16,    13,    12,     9,
     8,     0,    10,     0,    70,    69,    68,    65,    66,    72,
    73,    88,     0,    56,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,    39,     0,     0,    22,     0,
    83,    84,    86,    85,     0,     0,     0,    15,     0,    14,
    53,    55,    54,    51,     0,    58,    59,    60,    62,    61,
    63,     0,     0,     0,    36,    89,    90,    91,    78,     0,
    40,     0,    45,     0,    23,     0,     0,    52,    47,     0,
     0,    28,    24,     0,     0,     0,     0,    46,    44,     0,
     0,     0,    31,    26,     0,    50,    49,     0,    41,     0,
    29,     0,    25,     0,     0,    48,     0,     0,    34,    27,
    37,    42,    38,     0,    32,     0,    30,    33,     0,     0
};

static const short yydefgoto[] = {    18,
    19,    20,   144,   155,   172,   184,   173,   170,   188,   197,
   174,    21,    78,   157,    22,   117,   152,   180,   193,    23,
    34,   154,   169,    24,   166,   135,   159,    71,    72,    25,
    26,    27,    28,    29,    30,   103,    31
};

static const short yypact[] = {   516,
   -39,   -35,-32768,   -12,     3,    39,    43,    47,     9,    32,
    40,-32768,-32768,    68,   170,   170,-32768,    24,-32768,-32768,
-32768,-32768,-32768,-32768,   265,     4,-32768,    74,    76,   516,
    79,   107,    82,    80,   170,-32768,    81,    84,    98,   110,
   111,   134,-32768,   170,-32768,-32768,    41,   201,   112,   113,
-32768,   275,   114,   115,   516,   117,   124,   124,   124,   124,
   124,-32768,   124,   124,-32768,-32768,   263,-32768,   107,   107,
   -25,-32768,   308,    40,   122,   107,   228,   516,   170,   170,
    52,   104,   118,   120,   313,    72,-32768,-32768,-32768,-32768,
-32768,   263,-32768,   170,     4,     4,     4,     4,     4,-32768,
-32768,-32768,   516,-32768,   -20,   550,   170,   170,   131,   170,
   170,   170,   170,   170,   170,-32768,   107,   -18,-32768,   307,
   313,   313,-32768,-32768,   170,   170,   161,-32768,   270,   549,
-32768,-32768,-32768,-32768,   516,   313,   313,   313,   313,   313,
   313,    13,   137,   138,-32768,   313,   313,-32768,-32768,   351,
-32768,    82,-32768,   516,-32768,   179,   185,-32768,   192,   151,
   395,-32768,    51,   153,     2,   516,   152,-32768,-32768,   170,
   154,   155,   179,-32768,   107,-32768,-32768,   351,-32768,   516,
   313,   516,-32768,   155,    34,-32768,   439,   158,   549,-32768,
-32768,-32768,-32768,   516,   483,   162,-32768,-32768,   202,-32768
};

static const short yypgoto[] = {    59,
    21,-32768,-32768,-32768,-32768,-32768,    53,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,    46,-32768,-32768,    36,   -58,     0,   -15,
    26,    58,   -14,    57,   -11,   -90,    73
};


#define	YYLAST		597


static const short yytable[] = {    47,
    48,   128,    52,    53,     1,    32,    55,   107,   108,    33,
   104,   105,   107,   108,   107,   108,    73,   118,    75,    77,
   109,    40,    41,   199,    42,   131,     1,   143,    85,     2,
     3,     4,    35,     5,    63,    64,     6,     7,    51,     8,
     9,    49,    11,    12,    13,   107,   108,    50,    15,   176,
    36,    52,    53,    73,   106,    55,   151,    37,   142,   162,
    73,    38,   171,   121,   122,    39,   107,   108,    16,    60,
    61,    17,   123,   124,    54,    43,    52,    53,   129,   191,
    55,   183,    95,    96,    97,    98,    99,    51,    67,    44,
    56,    73,    73,   190,   136,   137,   138,   139,   140,   141,
    74,    73,   -78,   -78,    52,    53,   132,   133,    55,   146,
   147,    45,    51,    92,    52,    53,   185,    65,    55,    66,
   100,   101,    68,    54,    76,    46,    12,    13,    82,    83,
    79,    15,   156,    80,    52,    53,   120,   160,    55,    56,
    51,    69,    46,    12,    13,    52,    53,    81,    54,    55,
    51,    70,    84,   125,   181,    87,    88,    90,    91,    73,
    93,   130,    52,    53,    56,   116,    55,   126,    94,   127,
    51,    52,    53,    52,    53,    55,    54,    55,   134,    52,
    53,    51,   148,    55,   153,    17,    54,   162,    46,    12,
    13,   164,    56,   150,    15,   165,   167,   175,    51,   179,
   182,   200,    56,   102,   194,   198,    54,    51,   163,    51,
   177,     0,   161,   186,    16,    51,     0,    54,     0,     0,
     0,     0,    56,     0,   178,     0,    57,    58,    59,    60,
    61,     0,     0,    56,    54,     0,     0,     0,   187,     0,
   189,     0,     0,    54,     0,    54,    86,     0,     0,     0,
    56,    54,   195,    57,    58,    59,    60,    61,     0,    56,
     0,    56,     0,     0,     0,     1,     0,    56,     2,     3,
     4,     0,     5,   119,     0,     6,     7,     0,     8,     9,
    49,    11,    12,    13,     0,     0,    50,    15,     0,     0,
    57,    58,    59,    60,    61,    57,    58,    59,    60,    61,
    57,    58,    59,    60,    61,     0,     0,    16,    62,     1,
    17,   102,     2,     3,     4,   149,     5,     0,    89,     6,
     7,     0,     8,     9,    49,    11,    12,    13,     0,     0,
    50,    15,     0,    57,    58,    59,    60,    61,    57,    58,
    59,    60,    61,   110,   111,   112,   113,   114,   115,     0,
     0,    16,     0,     1,    17,   145,     2,     3,     4,     0,
     5,     0,     0,     6,     7,     0,     8,     9,    49,    11,
    12,    13,     0,     0,    50,    15,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,    16,     0,     1,    17,   158,
     2,     3,     4,     0,     5,     0,     0,     6,     7,     0,
     8,     9,    49,    11,    12,    13,     0,     0,    50,    15,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,    16,
     0,     1,    17,   168,     2,     3,     4,     0,     5,     0,
     0,     6,     7,     0,     8,     9,    49,    11,    12,    13,
     0,     0,    50,    15,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    16,     0,     1,    17,   192,     2,     3,
     4,     0,     5,   196,     0,     6,     7,     0,     8,     9,
    49,    11,    12,    13,     0,     0,    50,    15,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     1,     0,
     0,     2,     3,     4,     0,     5,     0,    16,     6,     7,
    17,     8,     9,    10,    11,    12,    13,     0,     0,    14,
    15,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     1,     0,     0,     2,     3,     4,     0,     5,     0,
    16,     6,     7,    17,     8,     9,    49,    11,    12,    13,
     0,     0,    50,    15,     0,    57,    58,    59,    60,    61,
     0,     0,     0,     0,     0,   110,   111,   112,   113,   114,
   115,     0,     0,    16,     0,    86,    17
};

static const short yycheck[] = {    15,
    16,    92,    18,    18,     3,    45,    18,    33,    34,    45,
    69,    70,    33,    34,    33,    34,    32,    76,    33,    35,
    46,    13,    14,     0,    16,    46,     3,    46,    44,     6,
     7,     8,    45,    10,    31,    32,    13,    14,    18,    16,
    17,    18,    19,    20,    21,    33,    34,    24,    25,    48,
    48,    67,    67,    69,    70,    67,    44,    19,   117,     9,
    76,    19,    12,    79,    80,    19,    33,    34,    45,    29,
    30,    48,    21,    22,    18,    44,    92,    92,    94,    46,
    92,   172,    57,    58,    59,    60,    61,    67,    30,    50,
    18,   107,   108,   184,   110,   111,   112,   113,   114,   115,
    19,   117,    31,    32,   120,   120,   107,   108,   120,   125,
   126,    44,    92,    55,   130,   130,   175,    44,   130,    44,
    63,    64,    44,    67,    45,    19,    20,    21,    19,    19,
    50,    25,   144,    50,   150,   150,    78,   152,   150,    67,
   120,    35,    19,    20,    21,   161,   161,    50,    92,   161,
   130,    45,    19,    50,   170,    44,    44,    44,    44,   175,
    44,   103,   178,   178,    92,    44,   178,    50,    45,    50,
   150,   187,   187,   189,   189,   187,   120,   189,    48,   195,
   195,   161,    22,   195,    48,    48,   130,     9,    19,    20,
    21,     7,   120,   135,    25,     4,    46,    45,   178,    48,
    47,     0,   130,    49,    47,    44,   150,   187,   156,   189,
   165,    -1,   154,   178,    45,   195,    -1,   161,    -1,    -1,
    -1,    -1,   150,    -1,   166,    -1,    26,    27,    28,    29,
    30,    -1,    -1,   161,   178,    -1,    -1,    -1,   180,    -1,
   182,    -1,    -1,   187,    -1,   189,    46,    -1,    -1,    -1,
   178,   195,   194,    26,    27,    28,    29,    30,    -1,   187,
    -1,   189,    -1,    -1,    -1,     3,    -1,   195,     6,     7,
     8,    -1,    10,    46,    -1,    13,    14,    -1,    16,    17,
    18,    19,    20,    21,    -1,    -1,    24,    25,    -1,    -1,
    26,    27,    28,    29,    30,    26,    27,    28,    29,    30,
    26,    27,    28,    29,    30,    -1,    -1,    45,    44,     3,
    48,    49,     6,     7,     8,    46,    10,    -1,    44,    13,
    14,    -1,    16,    17,    18,    19,    20,    21,    -1,    -1,
    24,    25,    -1,    26,    27,    28,    29,    30,    26,    27,
    28,    29,    30,    36,    37,    38,    39,    40,    41,    -1,
    -1,    45,    -1,     3,    48,    49,     6,     7,     8,    -1,
    10,    -1,    -1,    13,    14,    -1,    16,    17,    18,    19,
    20,    21,    -1,    -1,    24,    25,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    45,    -1,     3,    48,    49,
     6,     7,     8,    -1,    10,    -1,    -1,    13,    14,    -1,
    16,    17,    18,    19,    20,    21,    -1,    -1,    24,    25,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    45,
    -1,     3,    48,    49,     6,     7,     8,    -1,    10,    -1,
    -1,    13,    14,    -1,    16,    17,    18,    19,    20,    21,
    -1,    -1,    24,    25,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    45,    -1,     3,    48,    49,     6,     7,
     8,    -1,    10,    11,    -1,    13,    14,    -1,    16,    17,
    18,    19,    20,    21,    -1,    -1,    24,    25,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,     3,    -1,
    -1,     6,     7,     8,    -1,    10,    -1,    45,    13,    14,
    48,    16,    17,    18,    19,    20,    21,    -1,    -1,    24,
    25,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,     3,    -1,    -1,     6,     7,     8,    -1,    10,    -1,
    45,    13,    14,    48,    16,    17,    18,    19,    20,    21,
    -1,    -1,    24,    25,    -1,    26,    27,    28,    29,    30,
    -1,    -1,    -1,    -1,    -1,    36,    37,    38,    39,    40,
    41,    -1,    -1,    45,    -1,    46,    48
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 78 "yacc.y"
{reset();;
    break;}
case 2:
#line 79 "yacc.y"
{reset();;
    break;}
case 3:
#line 80 "yacc.y"
{reset();;
    break;}
case 4:
#line 81 "yacc.y"
{reset();;
    break;}
case 5:
#line 82 "yacc.y"
{reset();;
    break;}
case 6:
#line 83 "yacc.y"
{exit(EXIT_SUCCESS);;
    break;}
case 7:
#line 84 "yacc.y"
{print_symbol_table();;
    break;}
case 8:
#line 85 "yacc.y"
{reset();;
    break;}
case 9:
#line 86 "yacc.y"
{reset();;
    break;}
case 10:
#line 87 "yacc.y"
{reset();;
    break;}
case 11:
#line 88 "yacc.y"
{reset();;
    break;}
case 12:
#line 89 "yacc.y"
{reset();;
    break;}
case 13:
#line 90 "yacc.y"
{exit(EXIT_SUCCESS);;
    break;}
case 14:
#line 91 "yacc.y"
{;;
    break;}
case 15:
#line 92 "yacc.y"
{;;
    break;}
case 16:
#line 93 "yacc.y"
{print_symbol_table();;
    break;}
case 17:
#line 97 "yacc.y"
{;;
    break;}
case 18:
#line 98 "yacc.y"
{;;
    break;}
case 19:
#line 99 "yacc.y"
{;;
    break;}
case 20:
#line 100 "yacc.y"
{;;
    break;}
case 21:
#line 101 "yacc.y"
{;;
    break;}
case 22:
#line 104 "yacc.y"
{switch_expr();new_scope();;
    break;}
case 24:
#line 107 "yacc.y"
{int tmp = exit_scope(); printf("label%d%c:\nlabel%d:\n",tmp,'a'-1+next_case,tmp);;
    break;}
case 26:
#line 108 "yacc.y"
{int tmp = exit_scope();printf("label%d%c:\nlabel%d:\n",tmp,'a'-1+next_case,tmp);;
    break;}
case 28:
#line 109 "yacc.y"
{if(next_case>0)
								{printf("label%d%c:\n",nesting_arr[nesting_last_index],'a'-1+next_case);}
							next_case++;;
    break;}
case 29:
#line 112 "yacc.y"
{switch_test();;
    break;}
case 30:
#line 112 "yacc.y"
{;;
    break;}
case 31:
#line 113 "yacc.y"
{;;
    break;}
case 33:
#line 116 "yacc.y"
{printf("JMP label%d\n",nesting_arr[nesting_last_index]);;
    break;}
case 34:
#line 117 "yacc.y"
{;;
    break;}
case 35:
#line 119 "yacc.y"
{printf("label:%d\n",new_scope()); open_brace();;
    break;}
case 36:
#line 119 "yacc.y"
{close_brace();;
    break;}
case 37:
#line 119 "yacc.y"
{printf("JT R10,label%d\n",exit_scope());;
    break;}
case 38:
#line 121 "yacc.y"
{;;
    break;}
case 39:
#line 122 "yacc.y"
{printf("MOV RF,0\n");
								printf("label%d:\n",new_scope());reset();;
    break;}
case 40:
#line 124 "yacc.y"
{printf("JF R10, label%da\n",nesting_arr[nesting_last_index]);
								printf("CMPE RF,0\n");
								printf("JT R10, label%db\n", nesting_arr[nesting_last_index]);;
    break;}
case 41:
#line 127 "yacc.y"
{printf("label%db:\n",nesting_arr[nesting_last_index]);
							printf("MOV RF,1\n");
							open_brace();
							reset();;
    break;}
case 42:
#line 131 "yacc.y"
{printf("JMP label%d\n",nesting_arr[nesting_last_index]);
							printf("label%da:\n",exit_scope());
							close_brace();
						;
    break;}
case 43:
#line 137 "yacc.y"
{printf("label%d:\n",new_scope());;
    break;}
case 44:
#line 137 "yacc.y"
{;;
    break;}
case 45:
#line 139 "yacc.y"
{printf("JF R10, label%da\n",nesting_arr[nesting_last_index]);reset();open_brace();;
    break;}
case 46:
#line 140 "yacc.y"
{printf("JMP label%d\n",nesting_arr[nesting_last_index]);
													printf("label%da:\n",exit_scope());reset();close_brace();;
    break;}
case 47:
#line 143 "yacc.y"
{;;
    break;}
case 48:
#line 144 "yacc.y"
{;;
    break;}
case 49:
#line 145 "yacc.y"
{;;
    break;}
case 50:
#line 147 "yacc.y"
{printf("JT R10, label%d\n",new_scope());open_brace();reset();;
    break;}
case 51:
#line 148 "yacc.y"
{printf("JF R10, label%d\n",new_scope());open_brace();reset();;
    break;}
case 52:
#line 149 "yacc.y"
{printf("label%d:\n",exit_scope());close_brace();;
    break;}
case 53:
#line 153 "yacc.y"
{;;
    break;}
case 54:
#line 154 "yacc.y"
{cond_lowp("OR");;
    break;}
case 55:
#line 155 "yacc.y"
{cond_lowp("AND");;
    break;}
case 56:
#line 156 "yacc.y"
{printf("NOT R10\n");;
    break;}
case 57:
#line 157 "yacc.y"
{;;
    break;}
case 58:
#line 161 "yacc.y"
{cond_highp("CMPE");;
    break;}
case 59:
#line 162 "yacc.y"
{cond_highp("CMPNE");;
    break;}
case 60:
#line 163 "yacc.y"
{cond_highp("CMPGE");;
    break;}
case 61:
#line 164 "yacc.y"
{cond_highp("CMPG");;
    break;}
case 62:
#line 165 "yacc.y"
{cond_highp("CMPLE");;
    break;}
case 63:
#line 166 "yacc.y"
{cond_highp("CMPL");;
    break;}
case 64:
#line 171 "yacc.y"
{yyval.INTGR=yyvsp[-1].INTGR;;
    break;}
case 65:
#line 172 "yacc.y"
{ calc_lowp("ADD"); ;
    break;}
case 66:
#line 173 "yacc.y"
{ calc_lowp("SUB"); ;
    break;}
case 67:
#line 174 "yacc.y"
{
																												yyval.INTGR = ~yyvsp[0].INTGR;
																												if(after_hp)
																													printf("NOT R4\n");
																												else
																													printf("NOT R%d\n",next_reg-1);
																											;
    break;}
case 68:
#line 181 "yacc.y"
{ calc_lowp("OR"); ;
    break;}
case 69:
#line 182 "yacc.y"
{ calc_lowp("AND"); ;
    break;}
case 70:
#line 183 "yacc.y"
{ calc_lowp("XOR"); ;
    break;}
case 71:
#line 184 "yacc.y"
{	yyval.INTGR=yyvsp[0].INTGR;;
    break;}
case 72:
#line 187 "yacc.y"
{ calc_highp("MUL"); ;
    break;}
case 73:
#line 188 "yacc.y"
{ calc_highp("DIV"); ;
    break;}
case 74:
#line 189 "yacc.y"
{ yyval.INTGR=yyvsp[0].INTGR; ;
    break;}
case 75:
#line 193 "yacc.y"
{yyval.INTGR=yyvsp[0].INTGR;
																printf("MOV R%d, %d\n",next_reg++ ,yyvsp[0].INTGR);;
    break;}
case 76:
#line 195 "yacc.y"
{yyval.INTGR=yyvsp[0].FLT;
																printf("MOV R%d, %f\n",next_reg++,yyvsp[0].FLT);;
    break;}
case 77:
#line 197 "yacc.y"
{yyval.INTGR=yyvsp[0].INTGR;
																	if(declared[yyvsp[0].INTGR] == 1){
																		if(variable_initialized[yyvsp[0].INTGR] == 1){
																			yyval.INTGR=yyvsp[0].INTGR;
																			printf("MOV R%d, %c\n",next_reg++,yyvsp[0].INTGR+'a');
																		} else {
																			printf("Error: %c is not set\n", yyvsp[0].INTGR+'a');
																		}
																	} else {
																		printf("Error: %c is not declared\n", yyvsp[0].INTGR+'a');
																	}
																;
    break;}
case 78:
#line 209 "yacc.y"
{yyval.INTGR=yyvsp[-1].INTGR;;
    break;}
case 79:
#line 213 "yacc.y"
{	assign_only(yyvsp[-2].INTGR);;
    break;}
case 80:
#line 216 "yacc.y"
{ 	declare_only(yyvsp[0].INTGR,1);;
    break;}
case 81:
#line 217 "yacc.y"
{ 	declare_only(yyvsp[0].INTGR,2);;
    break;}
case 82:
#line 218 "yacc.y"
{ 	declare_only(yyvsp[0].INTGR,3);;
    break;}
case 83:
#line 219 "yacc.y"
{ 	declare_initalize(yyvsp[-2].INTGR,1);;
    break;}
case 84:
#line 220 "yacc.y"
{ 	declare_initalize(yyvsp[-2].INTGR,2);;
    break;}
case 85:
#line 221 "yacc.y"
{if(declared[yyvsp[-2].INTGR] == 0) {
																	declared[yyvsp[-2].INTGR] = 1;
																	type[yyvsp[-2].INTGR] = 3;
																	scope[yyvsp[-2].INTGR] = cscope;
																	is_constant[yyvsp[-2].INTGR] = 0;
																	variable_initialized[yyvsp[-2].INTGR] = 1;
																	printf("MOV %c,'%c'\n",yyvsp[-2].INTGR+'a',yyvsp[0].CHR+'a');

																} else {
																	printf("Syntax Error : %c is an already declared variable\n", yyvsp[-2].INTGR + 'a');
																}
															;
    break;}
case 86:
#line 233 "yacc.y"
{ printf("Syntax Error : char can not be assigned a floating number\n");;
    break;}
case 87:
#line 236 "yacc.y"
{ open_brace(); ;
    break;}
case 88:
#line 237 "yacc.y"
{ close_brace(); ;
    break;}
case 89:
#line 241 "yacc.y"
{ 	declare_const(yyvsp[-2].INTGR,1);
																						;
    break;}
case 90:
#line 244 "yacc.y"
{ 	declare_const(yyvsp[-2].INTGR,2);
																						;
    break;}
case 91:
#line 246 "yacc.y"
{
																								if(declared[yyvsp[-2].INTGR] == 0) {
																									declared[yyvsp[-2].INTGR] = 1;
																									type[yyvsp[-2].INTGR] = 3;
																									scope[yyvsp[-2].INTGR] = cscope;
																									is_constant[yyvsp[-2].INTGR] = 1;
																									variable_initialized[yyvsp[-2].INTGR] = 1;
																									printf("MOV %c,'%c'\n",yyvsp[-2].INTGR+'a',yyvsp[0].CHR+'a');

																								} else {
																									printf("Syntax Error : %c is an already declared variable\n", yyvsp[-2].INTGR + 'a');
																								}
																							;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 262 "yacc.y"

//Normal C-code
int main(void)
{
	return yyparse();
}
void print_symbol_table()
{
	printf("Symbol Table:\n=============\n");
	printf("Symbol\t\tType\t\tInitialized\t\tConstant\t\tScope\t\t\n");
	for (int i = 0 ; i < 26 ; i ++){
		if(declared[i] == 1)
		{
			printf("%c\t\t%s\t\t",i+'a',get_type(type[i]));
			if(variable_initialized[i] == 1)
				printf("true\t\t\t");
			else printf("false\t\t\t");
			if(is_constant[i] == 1)
				printf("true\t\t\t");
			else printf("false\t\t\t");

			printf("%d\n", scope[i]);
		}
	}
}
char * get_type(int type){
	if(type == 1)
		return "int";
	if(type == 2)
		return "float";
	if(type == 3)
		return "char";
}
void calc_lowp (char * op) {
	/*$$ = $1 + $3;*/
	if(is_first){
		printf("%s R0,R%d,R%d\n", op, --next_reg ,--next_reg );
		is_first=0;
	}
	else{
		if(after_hp){
			printf("%s R0,R%d,R4\n",op, --next_reg);
			after_hp = 0;
		}
		else{
			printf("%s R0,R%d,R0\n",op, --next_reg);
		}
		}
}

void calc_highp (char * op) {
	if(!after_hp){
		printf("%s R4,R%d,R%d\n", op, --next_reg ,--next_reg );
		after_hp = 1;
		is_first = 0;
	}
	else{
		printf("%s R4,R%d,R4\n", op, --next_reg );
	}
}

void cond_lowp (char * op) {
printf("%s R10,R10,R14\n",op);
}

void cond_highp (char * op) {
	if(!after_hp_cond){
		printf("%s R10,R%d,R%d\n", op, --next_reg ,--next_reg );
		after_hp_cond = 1;
		is_first_cond = 0;
	}
	else{
		printf("%s R14,R%d,R%d\n", op, --next_reg, --next_reg );
	}
}
void switch_test () {
	if(is_first){
		printf("CMPE R10,RS,R%d\n", --next_reg );
		is_first=0;
	}
	else{
		if(after_hp){
			printf("CMPE R10,RS,R4\n", --next_reg);
		}
		else{
			printf("CMPE R10,RS,R0\n", --next_reg);
		}
		}
		printf("JF R10,label%d%c\n",nesting_arr[nesting_last_index],'a'-1+next_case);
		reset();
}
void declare_only(int id,int type_)
{
	if(declared[id] == 0) {
	declared[id] = 1;
	type[id] = type_;
	scope[id] = cscope;
	variable_initialized[id] = 0;
	is_constant[id] = 0;
	} else {
		printf("Syntax Error : %c is an already declared variable\n", id + 'a');
	}
}
void assign_only(int id){
	if(declared[id] == 1) {
		if (is_constant[id] == 0) {
			variable_initialized[id] = 1;
			if(is_first){
				printf("MOV %c,R%d\n",id+'a',--next_reg);
				}else{
					if(after_hp)
						printf("MOV %c,R4\n",id+'a');
					else
						printf("MOV %c,R0\n",id+'a');
				}
			} else {
				printf("Syntax Error : %c is a constant\n", id + 'a');
			}
	} else {
		printf("Syntax Error : %c is not declared\n", id + 'a');
	}
}

void switch_expr(){
	if(is_first){
		printf("MOV RS,R%d\n",--next_reg);
		}else{
			if(after_hp)
				printf("MOV RS,R4\n");
			else
				printf("MOV RS,R0\n");
		}
	}

void declare_const(int id, int _type)
{
	if(declared[id] == 0) {
			declared[id] = 1;
			type[id] = _type;
			scope[id] = cscope;
			variable_initialized[id] = 1;
			is_constant[id] = 1;
			if(is_first){
				printf("MOV %c,R%d\n",id+'a',--next_reg);
		}else{
			if(after_hp)
				printf("MOV %c,R4\n",id+'a');
			else
				printf("MOV %c,R0\n",id+'a');
			}
	} else {
		printf("Syntax Error : %c is an already declared variable\n", id + 'a');
	}
}
void declare_initalize(int id, int _type){
	if(declared[id] == 0) {
		declared[id] = 1;
		type[id] = _type;
		scope[id] = cscope;
		variable_initialized[id] = 1;
		is_constant[id] = 0;
		if(is_first){
			printf("MOV %c,R%d\n",id+'a',--next_reg);
		}else{
			if(after_hp)
				printf("MOV %c,R4\n",id+'a');
			else
				printf("MOV %c,R0\n",id+'a');
			}
	} else {
		printf("Syntax Error : %c is an already declared variable\n", id + 'a');
	}
}
void reset()
{
	next_reg = 1;
	is_first = 1;
	after_hp = 0;
	is_first_cond = 1;
	after_hp_cond = 0;
	printf("\n");
}
int yyerror(char* s)
{
  fprintf(stderr, "%s\n",s);
  return 1;
}
int yywrap()
{
  return(1);
}

void open_brace() {
	cscope++;
}

void close_brace () {
	for (int i = 0; i < 26; i++) {
			if (scope[i] == cscope ) {
				scope[i] = -1;
				declared[i] = 0;
			}
	}
	cscope--;
}


int new_scope()
{
	opened_scopes ++;
	nesting_last_index ++;
	nesting_arr[nesting_last_index] = opened_scopes;
	return opened_scopes;
}
int exit_scope()
{
	int tmp = nesting_arr[nesting_last_index];
	nesting_last_index --;
	return tmp;
}
